export const config = {
  developer: {
    name: "Nitish Kumar Pandit",
    title: "Software Engineer",
    bio: "I turn ideas into full-stack products that are easy to use and accessible to everyone.",
    avatar: "https://i.pinimg.com/736x/d4/a5/f5/d4a5f585a3470cf0c42458970be37dbc.jpg",
  },
  social: {
    github: "nitishkumarpandittt",
    email: "workwithnitishhh@gmail.com",
    location: "Panchkula, Haryana",
  },
  projects: [
    {
      id: 1,
      title: "AI-Powered Code Review Assistant",
      description: "An intelligent code review platform that uses machine learning to analyze pull requests, detect bugs, suggest optimizations, and enforce coding standards.",
      image: "/projects/project-1.webp",
      technologies: ["Python", "TensorFlow", "React", "FastAPI", "PostgreSQL", "Docker"],
      github: "#",
      demo: "#",
    },
    {
      id: 2,
      title: "Real-time Collaborative Whiteboard",
      description: "A next-generation collaborative whiteboard platform with infinite canvas, real-time synchronization, and advanced drawing tools.",
      image: "/projects/project-2.webp",
      technologies: ["TypeScript", "WebRTC", "Socket.io", "Canvas API", "Node.js", "Redis"],
      github: "#",
      demo: "#",
    },
    {
      id: 3,
      title: "Blockchain Voting System",
      description: "A secure, transparent, and decentralized voting platform built on Ethereum. Features smart contract-based voting and anonymous ballots.",
      image: "/projects/project-3.webp",
      technologies: ["Solidity", "Web3.js", "React", "Ethereum", "IPFS", "MetaMask"],
      github: "#",
      demo: "#",
    },
    {
      id: 4,
      title: "Cloud Infrastructure Dashboard",
      description: "A comprehensive cloud management platform for monitoring, managing, and optimizing multi-cloud infrastructure.",
      image: "/projects/project-4.webp",
      technologies: ["Go", "Kubernetes", "Grafana", "Prometheus", "Terraform", "React"],
      github: "#",
      demo: "#",
    },
    {
      id: 5,
      title: "Neural Network Visualizer",
      description: "An interactive web application for visualizing, training, and experimenting with neural networks.",
      image: "/projects/project-5.webp",
      technologies: ["Python", "TensorFlow.js", "D3.js", "Next.js", "WebGL", "TypeScript"],
      github: "#",
      demo: "#",
    },
  ],
  skills: [
    { name: "React.js", icon: "react" },
    { name: "Next.js", icon: "nextjs" },
    { name: "Node.js", icon: "nodejs" },
    { name: "TypeScript", icon: "typescript" },
    { name: "JavaScript", icon: "javascript" },
    { name: "TailwindCSS", icon: "tailwind" },
    { name: "MongoDB", icon: "mongodb" },
    { name: "Express", icon: "express" },
    { name: "Git", icon: "git" },
    { name: "AWS", icon: "aws" },
    { name: "Docker", icon: "docker" },
    { name: "Framer Motion", icon: "framer" },
  ],
};

